appset:
  environment: "cpin"
  namespace: "argocd-cpin"
  argoProject: "infrastructure"

  # Valeurs par défaut utilisées pour les composants si elles ne sont pas spécifiées
  default:
    branch: "main"
    repoUrl: "https://github.com/my-org/my-repo.git"
    destination: "https://kubernetes.default.svc"
    syncPolicy:
      prune: true
      selfHeal: true
    ServerSideApply: true
    
components:
  - name: "kyverno"
    namespace: "kyverno-cpin"
    branch: "main"
    repoUrl: "https://github.com/cloud-pi-native/cpin-external-cluster.git"
    destination: "https://kubernetes.default.svc"
    parameters: {}