{{- range .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  annotations:
    helm.sh/hook: post-install,post-upgrade  # Le hook pour exécuter après l'installation
spec:
  description: {{ .description | quote }}
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
    {{- range .sourceRepos }}
    - {{ . | quote }}
    {{- end }}
  destinations:
    {{- range .destinations }}
    - namespace: {{ .namespace | quote }}
      server: {{ .server | quote }}
    {{- end }}
---
{{- end }}