

sourceRepos:
  - "https://github.com/cloud-pi-native/cpin-external-cluster.git"

cpin:
  apps:
    - name: "cert-manager"
      namespace: "certmanager-cpin"
      valuefile: "./values-cpin.yaml"
      branch: "main"
      repoUrl: "https://github.com/cloud-pi-native/cpin-external-cluster.git"
      parameters: {}
    - name: "kyverno"
      namespace: "kyverno-cpin"
      valuefile: "./values-cpin.yaml"
      branch: "main"
      repoUrl: "https://github.com/cloud-pi-native/cpin-external-cluster.git"
      parameters: {}
    - name: "kyverno-rules"
      namespace: "kyverno-cpin"
      valuefile: "./values.yaml"
      branch: "main"
      repoUrl: "https://github.com/cloud-pi-native/cpin-external-cluster.git"
      parameters: {}
    - name: "falco"
      namespace: "falco-cpin"
      valuefile: "./values.yaml"
      branch: "main"
      repoUrl: "https://github.com/cloud-pi-native/cpin-external-cluster.git"
      parameters: {}
    - name: "minio-operator"
      namespace: "minio-cpin"
      valuefile: "./values.yaml"
      branch: "main"
      repoUrl: "https://github.com/cloud-pi-native/cpin-external-cluster.git"
      parameters: {}
