{{- if .Values.quota.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-ns-quota
  annotations:
    policies.kyverno.io/title: Add Quota
    policies.kyverno.io/category: Multi-Tenancy, Best Practices, LimitRange
    policies.kyverno.io/subject: ResourceQuota, LimitRange
    policies.kyverno.io/severity: low
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      To better control the number of resources that can be created in a given Namespace and provide default resource consumption limits for Pods, ResourceQuota and LimitRange resources are recommended. This policy will generate ResourceQuota and LimitRange resources when a new Namespace is created.
spec:
  background: false
  rules:
  - name: generate-resourcequota
#    skipBackgroundRequests: true
    match:
      any:
      - resources:
          kinds:
          - Namespace
    generate:
      apiVersion: v1
      kind: ResourceQuota
      name: default-resourcequota
      synchronize: true
      namespace: "{{`{{ request.object.metadata.name }}`}}"
      data:
        spec:
          hard:
            requests.cpu: '{{ .Values.quota.request.cpu }}'
            requests.memory: '{{ .Values.quota.request.memory }}'
            limits.cpu: '{{ .Values.quota.limits.cpu }}'
            limits.memory: '{{ .Values.quota.limits.memory }}'
    exclude:
      any:
      - resources:
          namespaces:
            {{- range .Values.excludedNamespaces }}
            - "{{ . }}"
            {{- end }}
{{- end }}